"""Phase 3 exception workflow

Revision ID: 9f5209bf0adf
Revises: bd2c71df2301
Create Date: 2026-08-26 21:50:07.928124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5209bf0adf'
down_revision: Union[str, Sequence[str], None] = 'bd2c71df2301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exception_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exception_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('comment_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exception_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exception_comments_id'), ['id'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_audit_logs_loan_id'), ['loan_id'], unique=False)

    with op.batch_alter_table('exceptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('assigned_to', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('resolution_reason', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))
        pass

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exceptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('version')
        batch_op.drop_column('resolution_reason')
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('assigned_to')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_loan_id'))
        batch_op.drop_column('loan_id')

    with op.batch_alter_table('exception_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exception_comments_id'))

    op.drop_table('exception_comments')
    # ### end Alembic commands ###
