"""Add cross source fields to normalized loan

Revision ID: bd2c71df2301
Revises: d9bfcde51bb7
Create Date: 2026-08-26 21:36:49.127674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'bd2c71df2301'
down_revision: Union[str, Sequence[str], None] = 'd9bfcde51bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exceptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('actual_value', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('expected_condition', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        pass
        batch_op.drop_column('rule_id')
        batch_op.drop_column('ai_recommendation')

    with op.batch_alter_table('normalized_loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servicer_update_current_balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('servicer_update_interest_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('servicer_update_payment_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('servicer_update_days_past_due', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('servicer_update_servicer_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('servicer_update_last_payment_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('servicer_update_last_updated_at', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('servicer_update_document_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('manifest_document_status', sa.String(), nullable=True))

    with op.batch_alter_table('raw_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_raw_records_loan_id'), ['loan_id'], unique=False)

    with op.batch_alter_table('upload_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_batches', schema=None) as batch_op:
        batch_op.drop_column('source_type')

    with op.batch_alter_table('raw_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_records_loan_id'))
        batch_op.drop_column('loan_id')

    with op.batch_alter_table('normalized_loans', schema=None) as batch_op:
        batch_op.drop_column('manifest_document_status')
        batch_op.drop_column('servicer_update_document_status')
        batch_op.drop_column('servicer_update_last_updated_at')
        batch_op.drop_column('servicer_update_last_payment_date')
        batch_op.drop_column('servicer_update_servicer_name')
        batch_op.drop_column('servicer_update_days_past_due')
        batch_op.drop_column('servicer_update_payment_status')
        batch_op.drop_column('servicer_update_interest_rate')
        batch_op.drop_column('servicer_update_current_balance')

    with op.batch_alter_table('exceptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_recommendation', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('rule_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'validation_rules', ['rule_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('expected_condition')
        batch_op.drop_column('actual_value')
        batch_op.drop_column('field')

    # ### end Alembic commands ###
