"""Phase 2 models

Revision ID: d9bfcde51bb7
Revises: 
Create Date: 2026-08-26 21:34:26.524109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9bfcde51bb7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('validation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('rule_definition', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_rules_id'), 'validation_rules', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('upload_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_batches_id'), 'upload_batches', ['id'], unique=False)
    op.create_table('raw_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('row_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['upload_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_records_id'), 'raw_records', ['id'], unique=False)
    op.create_table('validation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('run_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['upload_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_runs_id'), 'validation_runs', ['id'], unique=False)
    op.create_table('normalized_loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_record_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('loan_id', sa.String(), nullable=True),
    sa.Column('borrower_id', sa.String(), nullable=True),
    sa.Column('loan_type', sa.String(), nullable=True),
    sa.Column('origination_date', sa.Date(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('original_principal', sa.Float(), nullable=True),
    sa.Column('current_balance', sa.Float(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('term_months', sa.Integer(), nullable=True),
    sa.Column('borrower_state', sa.String(), nullable=True),
    sa.Column('loan_purpose', sa.String(), nullable=True),
    sa.Column('credit_grade', sa.String(), nullable=True),
    sa.Column('employment_length', sa.String(), nullable=True),
    sa.Column('income_band', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('days_past_due', sa.Integer(), nullable=True),
    sa.Column('servicer_name', sa.String(), nullable=True),
    sa.Column('last_payment_date', sa.Date(), nullable=True),
    sa.Column('last_updated_at', sa.Date(), nullable=True),
    sa.Column('document_status', sa.String(), nullable=True),
    sa.Column('source_system', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['upload_batches.id'], ),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_loans_borrower_id'), 'normalized_loans', ['borrower_id'], unique=False)
    op.create_index(op.f('ix_normalized_loans_id'), 'normalized_loans', ['id'], unique=False)
    op.create_index(op.f('ix_normalized_loans_loan_id'), 'normalized_loans', ['loan_id'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('normalized_loan_id', sa.Integer(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['normalized_loan_id'], ['normalized_loans.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['validation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_id'), 'validation_results', ['id'], unique=False)
    op.create_table('verified_loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_loan_id', sa.Integer(), nullable=True),
    sa.Column('verified_data', sa.JSON(), nullable=True),
    sa.Column('verified_by_user_id', sa.Integer(), nullable=True),
    sa.Column('verification_timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('record_hash', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['original_loan_id'], ['normalized_loans.id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verified_loans_id'), 'verified_loans', ['id'], unique=False)
    op.create_table('exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('validation_result_id', sa.Integer(), nullable=True),
    sa.Column('normalized_loan_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('rule_name', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('ai_recommendation', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['normalized_loan_id'], ['normalized_loans.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['validation_rules.id'], ),
    sa.ForeignKeyConstraint(['validation_result_id'], ['validation_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exceptions_id'), 'exceptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exceptions_id'), table_name='exceptions')
    op.drop_table('exceptions')
    op.drop_index(op.f('ix_verified_loans_id'), table_name='verified_loans')
    op.drop_table('verified_loans')
    op.drop_index(op.f('ix_validation_results_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_normalized_loans_loan_id'), table_name='normalized_loans')
    op.drop_index(op.f('ix_normalized_loans_id'), table_name='normalized_loans')
    op.drop_index(op.f('ix_normalized_loans_borrower_id'), table_name='normalized_loans')
    op.drop_table('normalized_loans')
    op.drop_index(op.f('ix_validation_runs_id'), table_name='validation_runs')
    op.drop_table('validation_runs')
    op.drop_index(op.f('ix_raw_records_id'), table_name='raw_records')
    op.drop_table('raw_records')
    op.drop_index(op.f('ix_upload_batches_id'), table_name='upload_batches')
    op.drop_table('upload_batches')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_validation_rules_id'), table_name='validation_rules')
    op.drop_table('validation_rules')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
